gdg-busan-django/mysite/blog/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
  # Example: /
  url(r'^$', PostLV.as_view(), name='index'),
  # Example: /post/ (same as /)
  url(r'^post/$', PostLV.as_view(), name='post_list'),
  # Example: /post/django-example/
  url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
  # Example: /archive/
  url(r'^archive/$', PostAV.as_view(), name='post_archive'),

  # Example: /2016/
  url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
  # Example: /2016/11/
  url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),
  # Example: /2016/11/20
  url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
  # Example: /today/
  url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

  # Example: /tag/
  url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
  # Example: /tag/tagname/
  url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

]

gdg-busan-django/mysite/bookmark/urls.py
from django.conf.urls import url
from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
  url(r'^$', BookmarkLV.as_view(), name='index'),
  url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
]

gdg-busan-django/mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^admin/', admin.site.urls),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gdg-busan-django/mysite/photo/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
]

gdg-busan-django/mysite/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import TagField

# Create your models here.
class Post(models.Model):
  title = models.CharField('TITLE', max_length=50)
  slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title aliax.')
  description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
  content = models.TextField('CONTENT')
  create_date = models.DateTimeField('Create Date', auto_now_add=True)
  modify_date = models.DateTimeField('Modify Date', auto_now=True)
  tag = TagField()

  class Meta:
    verbose_name = 'post'
    verbose_name_plural = 'posts'
    db_table = 'my_post'
    ordering = ('-modify_date',)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse('blog:post_detail', args=(self.slug,))

  def get_previous_post(self):
    return self.get_previous_by_modify_date()

  def get_next_post(self):
    return self.get_next_by_modify_date()

gdg-busan-django/mysite/bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
  title = models.CharField(max_length=100, blank=True, null=True)
  url = models.URLField('url', unique=True)
  def __str__(self):
    return "%s %s" %(self.title, self.url)

gdg-busan-django/mysite/photo/models.py
from django.db import models
from django.core.urlresolvers import reverse

from .fields import ThumbnailImageField

# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

gdg-busan-django/mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView
from django.views.generic.dates import YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView


from .models import Post
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

# Create your views here.
#-- ListView
class PostLV(ListView) :
  model = Post
  template_name = 'blog/post_all.html'
  context_object_name = 'posts'
  paginate_by = 2

#-- DetailView
class PostDV(DetailView) :
  model = Post

#-- ArchiveView
class PostAV(ArchiveIndexView) :
  model = Post
  date_field = 'modify_date'
  month_format = '%m'

class PostYAV(YearArchiveView) :
  model = Post
  date_field = 'modify_date'
  make_object_list =True
  month_format = '%m'

class PostMAV(MonthArchiveView) :
  model = Post
  date_field = 'modify_date'
  month_format = '%m'

class PostDAV(DayArchiveView) :
  model = Post
  date_field = 'modify_date'
  month_format = '%m'

class PostTAV(TodayArchiveView) :
  model = Post
  date_field = 'modify_date'
  month_format = '%m'


#--- TemplateView
class TagTV(TemplateView) :
  template_name = 'tagging/tagging_cloud.html'

class PostTOL(TaggedObjectList):
  model = Post
  template_name = 'tagging/tagging_post_list.html'

gdg-busan-django/mysite/bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.

# list view
class BookmarkLV(ListView):
  model = Bookmark

# detail view
class BookmarkDV(DetailView):
  model = Bookmark

gdg-busan-django/mysite/mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

gdg-busan-django/mysite/photo/views.py
from django.views.generic import ListView, DetailView
from .models import Album, Photo

# Create your views here.
class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

gdg-busan-django/mysite/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %} Django Blog Post All {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>블로그 목록페이지 입니다.</h3>
    <hr>

    <div id="content">
        {% for post in posts %}
            <h5><a href='{{post.get_absolute_url}}'>{{post.title}}</a></h5>
            {{post.modify_date|date:"N d, Y"}}
            <p>{{post.description}}</p>
        {% endfor %}
        <br/>
        <div>
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page={{page_obj.previous_page_number}}">PreviousPage</a>
                {% endif %}
                page {{page_obj.number}} of {{ page_obj.paginator.num_pages}}
                {% if page_obj.has_next %}
                    <a href="?page={{page_obj.next_page_number}}">NextPage</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %} Django Blog Archive {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>블로그 아카이브 입니다.</h3>
    <hr>

    <div id="content">
        <h1>Post Archives until {% now "N d, Y" %}</h1>
        <ul>
            {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
            {% endfor %}
        </ul>
        <br/>
        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>

    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %} Django Blog Archive Day {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>블로그 일별 아카이브 입니다.</h3>
    <hr>

    <div id="content">
        <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %} Django Blog Archive Month {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>블로그 월별 아카이브 입니다.</h3>
    <hr>

    <div id="content">
        <h1>Post Archives or {{ day|date:"Y-m-d"}}</h1>
        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %} Django Blog Archive Year {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>블로그 연별 아카이브 입니다.</h3>
    <hr>

    <div id="content">
        <h1>Post Archives or {{ month|date:"N, Y"}}</h1>
        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %} Django Blog Detail {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>블로그 상세페이지 입니다.</h3>
    <hr>

    <div id="content">
        <h2>{{ object.title }}</h2>

        <p class="other_posts">
            {% if object.get_previous_by_modify_date %}
                <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">&laquo;--{{ object.get_previous_post }}</a>
            {% endif %}

            {% if object.get_next_by_modify_date %}
                <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{object.get_next_post}}--&raquo;</a>
            {% endif %}
        </p>

        <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
        <br/>

        <div class="body">
            {{ object.content|linebreaks }}
        </div>
        <hr>

        <div>
            <b>TAGS: </b>
            {% load tagging_tags %}
            {% tags_for_object object as tags %}
            {% for tag in tags %}
            <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
            {% endfor %}
            <a href="{% url 'blog:tag_cloud' %}"><i>[ TagCloud ]</i></a>
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/tagging/tagging_cloud.html
{% extends "base.html" %}

{% block title %} Django Blog Tag Cloud {% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}

<br/><br/>
<div class="container">
    <h3>태그 페이지 입니다.</h3>
    <hr>

    <div id="content">
        <div class="tag-cloud">
            {% load tagging_tags %}
            {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
            {% for tag in tags %}
            <span class="tag-{{tag.font_size}}">
                <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}({{tag.font_size}})</a>
            </span>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/blog/templates/tagging/tagging_post_list.html
{% extends "base.html" %}

{% block title %} Django Blog Tag Post List {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>태그된 포스트 목록페이지 입니다.</h3>
    <hr>

    <div id="content">
        <h4>Posts for tag - {{ tag.name }}</h4>
        <br>

        {% for post in object_list %}
            <h5><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h5>
            {{ post.modify_date|date:"N d, Y" }}
            <p>{{ post.description }}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %} Django Bookmark Detail {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>북마크 상세페이지 입니다.</h3>

    <hr>

    <div id="content">
        <h1>{{ object.title }}</h1>
        <ul>
            <li>
              URL : <a href="{{ object.url }}">{{ object.url }}</a>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %} Django Bookmark List {% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h3>북마크 목록페이지 입니다.</h3>

    <hr>

    <div id="content">
        <ul>
            {% for bookmark in object_list %}
            <li>
            <a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %} Django Blog Post All {% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}

<br/><br/>
<div class="container">
    <h3>사진 앨범 상세페이지 입니다.</h3>
    <hr>

    <div id="content">
        <h2 style="display:inline">{{ object.name }}</h2>
        &emsp;<b><i>{{ object.description }}</i></b>

        <hr/>

        <div class="album-detail">
            {% for photo in object.photo_set.all %}
            <div class="album-detail-photo">
                <a href="{{ photo.get_absolute_url }}">
                <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
                </a>
                <li>{{ photo.title }}</li>
                <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %} Django Blog Post All {% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}

<br/><br/>
<div class="container">
    <h3>사진 앨범 목록페이지 입니다.</h3>
    <hr>

    <div id="content">
        {% for item in object_list %}
        <div class="clear_float">
            <h5 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h5>
            &emsp;<b><i>{{ item.description }}</i></b>
        </div>

        <hr/>

        <div class="album-list">
            {% for photo in item.photo_set.all|slice:":5" %}
            <div class="album-list-photo">
                <a href="{{ photo.get_absolute_url }}">
                <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
                </a>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

gdg-busan-django/mysite/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %} Django Blog Post All {% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}

<br/><br/>
<div class="container">
    <h3>사진 상세페이지 입니다.</h3>
    <hr>

    <div id="content">
        <h2>{{ object.title }}</h2>

        <table class="photo-detail">
            <tr>
                <td>
                    <a href="{{ object.image.url }}">
                    <img style="max-width:100%" src="{{ object.image.url }}" />
                    </a>
                </td>
                <td>
                    <ul>
                        <li>Photo Description</li>
                        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                        {% else %}<p>(blank)</p>{% endif %}
                        <li>Date Uploaded</li>
                        <p>{{ object.upload_date }}</p>
                        <li>Album Name</li>
                        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
                    </ul>
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}

gdg-busan-django/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} By Djangooooo{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" />
</head>
<body>

    <nav class="navbar navbar-static-top navbar-light bg-faded">
      <a class="navbar-brand" href="/">anpaul0615</a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/bookmark">Bookmark</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/blog">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/photo">Photo</a>
        </li>
      </ul>
      <ul class="nav navbar-nav float-xs-right">
        <li class="nav-item">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
      </ul>
    </nav>

    {% block content %}{% endblock %}

    <hr/>

    <div class="container">
        <footer>
            <p>&copy; 2016 Copyright.</p>
        </footer>
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/js/bootstrap.min.js"></script>
</body>
</html>

gdg-busan-django/mysite/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% block extrastyle %}{% static 'css/carousel.css' %}{% endblock %}

{% block title %}home.html{% endblock %}
{% block content %}

<br/><br/>
<div class="container">
    <h1>인덱스페이지 입니다.</h1>
</div>

{% endblock %}