winerama-demo/winerama/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'  ## ??

urlpatterns = [
  path('', views.review_list, name='review_list'),
  path('<int:review_id>/', views.review_detail, name='review_detail'),
  path('wines/', views.wine_list, name='wine_list'), 
  path('wines/<int:wine_id>/', views.wine_detail, name='wine_detail'),
  path('wines/<int:wine_id>/new/', views.add_review, name='add_review'),
]

winerama-demo/winerama/winerama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('reviews/', include('reviews.urls', namespace='reviews')), ## namespace 와 app 경로를 맞춰주는게 관례
    path('admin/', admin.site.urls),
]

winerama-demo/winerama/reviews/models.py
from django.db import models
import numpy as np


class Wine(models.Model):
  name = models.CharField(max_length=200)

  def average_rating(self):
    all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
    return np.mean(all_ratings)

  def __str__(self):
    return self.name
    

class Review(models.Model):
  RATING_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
  )

  wine = models.ForeignKey(Wine, on_delete=models.PROTECT)
  pub_date = models.DateTimeField('date published')
  user_name = models.CharField(max_length=100)
  comment = models.CharField(max_length=200)
  rating = models.IntegerField(choices=RATING_CHOICES)

  # def __str__(self):
  #   return self.wine.name + " (powerd by " + self.user_name + ")"
    

winerama-demo/winerama/reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review

class ReviewForm(ModelForm):  ## django 에서 제공하는 forms 양식/기능 사용
  class Meta:
    model = Review
    fields = ['user_name', 'rating', 'comment']
    widgets = {
      'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
    }
    

winerama-demo/winerama/reviews/views.py
from django.shortcuts import render, get_object_or_404
from .models import Review, Wine

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import ReviewForm
import datetime


def review_list(request):
  latest_review_list = Review.objects.order_by('-pub_date')[:9]
  context = { 'latest_review_list': latest_review_list }
  return render(request, 'reviews/review_list.html', context)

def review_detail(request, review_id):
  review = get_object_or_404(Review, pk=review_id)
  context = { 'review': review }
  return render(request, 'reviews/review_detail.html', context)

def wine_list(request):
  wine_list = Wine.objects.order_by('-name')
  context = { 'wine_list': wine_list }
  return render(request, 'reviews/wine_list.html', context)

def wine_detail(request, wine_id):
  wine = get_object_or_404(Wine, pk=wine_id)
  form = ReviewForm()
  context = { 'wine': wine, 'form': form }
  return render(request, 'reviews/wine_detail.html', context)

def add_review(request, wine_id):
  wine = get_object_or_404(Wine, pk=wine_id)
  if request.POST:
    form = ReviewForm(request.POST)
  else:
    form = ReviewForm()
  if form.is_valid():
    user_name = request.user.username
    review = form.save(commit=False)
    review.wine = wine
    review.user_name = user_name
    review.pub_date = datetime.datetime.now()
    review.save()
    return HttpResponseRedirect(reverse_lazy('reviews:wine_detail', args=(wine.id,)))
  context = {'wine': wine, 'form': form}
  return render(request, 'reviews/wine_detail.html', context)

winerama-demo/winerama/reviews/templates/reviews/review_detail.html
<h4>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>

winerama-demo/winerama/reviews/templates/reviews/review_list.html
<h2>Latest reviews</h2>

{% if latest_review_list %}
<div>
  {% for review in latest_review_list %}
  <div>
    <h4><a href="{% url 'reviews:review_detail' review.id %}">{{ review.wine.name }}</a></h4>
    <h6>rated {{ review.rating }} of 5 by {{ review.user_name }} </h6>
    <p>{{ review.comment }}</p>
  </div>
  {% endfor %}
</div>

{% else %}
<p>No reviews are available.</p>

{% endif %}

winerama-demo/winerama/reviews/templates/reviews/wine_detail.html
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div>
  {% for review in wine.review_set.all %} {% comment %} review_set 은 ORM 기능임!! {% endcomment %}
  <div>
  <em>{{ review.comment }}</em>
  <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
  <h5><a href="{% url 'reviews:review_detail' review.id %}">Read more</a></h5>
  </div>
  {% endfor %}
</div>

<h3>Add your review</h3>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>

{% endif %}
<form action="{% url 'reviews:add_review' wine.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add" />
</form>

{% else %}
<p>No reviews for this wine yet</p>

{% endif %}

winerama-demo/winerama/reviews/templates/reviews/wine_list.html
<h2>Wine list</h2>

{% if wine_list %}
<div>
  {% for wine in wine_list %}
  <div>
    <h4><a href="{% url 'reviews:wine_detail' wine.id %}">{{ wine.name }}</a></h4>
    <h5>{{ wine.review_set.count }} reviews</h5>
    <h5>{{ wine.average_rating | floatformat }} average rating</h5>
  </div>
  {% endfor %}
</div>

{% else %}
<p>No wines are available.</p>

{% endif %}